Plugin Name: gcTimer
App Version: 3.6.2
Server Main: com.growcontrol.plugins.gctimer.server.gcTimer.class
Client Main: com.growcontrol.plugins.gctimer.client.gcTimer.class
Author: lorenzop
Website: http://growcontrol.com/
Depend: []
SoftDepend: []
