Plugin Name: gcTimer
Plugin Version: 5.6.1
Server Main: com.growcontrol.plugins.gctimer.server.gcTimer.class
Client Main: com.growcontrol.plugins.gctimer.client.gcTimer.class
Author: lorenzop
Website: http://growcontrol.com/
Depend: []
SoftDepend: []